FROM openjdk:17-jdk-bullseye as builder
COPY . /tmp/qprov
WORKDIR /tmp/qprov
RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
RUN unzip apache-maven-3.8.8-bin.zip
RUN PATH=$PATH:/tmp/qprov/apache-maven-3.8.8/bin mvn package -DskipTests

FROM eclipse-temurin:17-jdk
LABEL maintainer = "Benjamin Weder <benjamin.weder@iaas.uni-stuttgart.de>"

ENV SERVER_PORT 5020

COPY --from=builder /tmp/qprov/org.quantil.qprov.web/target/org.quantil.qprov.web.jar /app/

RUN apt update && apt install -y graphviz

WORKDIR /app

ENTRYPOINT ["java","-jar","org.quantil.qprov.web.jar"]
