FROM maven:3.6.3-jdk-14 as builder
COPY . /tmp/qprov
WORKDIR /tmp/qprov
RUN mvn package -DskipTests

FROM openjdk:16-jdk-alpine
LABEL maintainer = "Benjamin Weder <benjamin.weder@iaas.uni-stuttgart.de>"

ENV SERVER_PORT 8080
ENV QPROV_IBMQ_EXECUTE_CIRCUITS false
ENV QPROV_IBMQ_AUTO_COLLECT false
ENV QPROV_IBMQ_AUTO_COLLECT_INTERVAL 60
ENV QPROV_IBMQ_AUTO_COLLECT_INTERVAL_CIRCUITS 180
ENV QISKIT_SERVICE_HOSTNAME qiskit-service
ENV QISKIT_SERVICE_PORT 5000

COPY --from=builder /tmp/qprov/org.quantil.qprov.collector/target/org.quantil.qprov.collector.jar /app/

WORKDIR /app

ENTRYPOINT ["java","-jar","org.quantil.qprov.collector.jar"]
