FROM maven:3.6.3-adoptopenjdk-14 as builder
COPY . /tmp/qprov
WORKDIR /tmp/qprov
RUN mvn package -DskipTests

FROM eclipse-temurin:16-jdk
LABEL maintainer = "Benjamin Weder <benjamin.weder@iaas.uni-stuttgart.de>"

ENV SERVER_PORT 5020

COPY --from=builder /tmp/qprov/org.quantil.qprov.web/target/org.quantil.qprov.web.jar /app/

RUN apt update && apt install -y graphviz

WORKDIR /app

ENTRYPOINT ["java","-jar","org.quantil.qprov.web.jar"]
