# spring boot
spring:
  output: { ansi: { enabled: ALWAYS } }
  mvc: { log-request-details: true }
  jackson: { serialization: { WRITE_DATES_AS_TIMESTAMPS: false } }
  jpa:
    generate-ddl: true
    hibernate: { use-new-id-generator-mappings: false, ddl-auto: update }
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
  datasource:

    url: "jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:qprov}"
    driver-class-name: org.postgresql.Driver
    username: "${POSTGRES_USER:qprov}"
    password: "${POSTGRES_PASSWORD:qprov}"
    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: UTF-8

# tomcat
server:
  port: ${SERVER_PORT:5021}
  servlet:
    contextPath: "/qprov-collector"

# logging
logging:
  level:
    mvc: "${LOGGING_LEVEL_MVC:debug}"
    org.quantil.qprov: "${LOGGING_LEVEL_QPROV:debug}"
    springdoc: "${LOGGING_LEVEL_SPRINGDOC:debug}"
    springframework: "${LOGGING_LEVEL_SPRINGFRAMEWORK:debug}"
    web: "${LOGGING_LEVEL_WEB:debug}"
    org.hibernate.orm.deprecation: "${LOGGING_LEVEL_HIBERNATE_ORM:error}"

# config
qprov:
  ibmq:
    token: "${QPROV_IBMQ_TOKEN:b9fa89e0ff409a33d5fe8ef317df65bd24c3a60dc765401afcad2ce203f55f584b157b4db6b536b2fcc886ad71421912f9a38cbeb3afa330864805cbb1c43307}"
    execute-calibration: ${QPROV_IBMQ_EXECUTE_CIRCUITS:false}
    auto-collect: ${QPROV_IBMQ_AUTO_COLLECT:true}
    auto-collect-interval: ${QPROV_IBMQ_AUTO_COLLECT_INTERVAL:1}
    auto-collect-interval-circuits: ${QPROV_IBMQ_AUTO_COLLECT_INTERVAL_CIRCUITS:180}
    qiskit-service:
      hostname: "${QISKIT_SERVICE_HOSTNAME:127.0.0.1}"
      port: ${QISKIT_SERVICE_PORT:5013}
      version: "v1.0"
