# spring boot
spring:
  output: {ansi: {enabled: ALWAYS}}
  mvc: {log-request-details: true}
  jackson: {serialization: {WRITE_DATES_AS_TIMESTAMPS: false}}
  jpa:
    generate-ddl: true
    hibernate: {use-new-id-generator-mappings: false, ddl-auto: update}
    show-sql: false
    properties: {hibernate: {dialect: org.hibernate.dialect.PostgreSQLDialect}}
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOSTNAME:127.0.0.1}:${POSTGRES_PORT:5060}/${POSTGRES_DB:qprov}"
    driver-class-name: org.postgresql.Driver
    username: "${POSTGRES_USER:qprov}"
    password: "${POSTGRES_PASSWORD:qprov}"
    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: UTF-8

# tomcat
server:
  port: ${SERVER_PORT:5020}
  servlet:
    contextPath: "/qprov"

# logging
logging:
  level:
    mvc: "${LOGGING_LEVEL_MVC:debug}"
    org.quantil.qprov: "${LOGGING_LEVEL_QPROV:debug}"
    springdoc: "${LOGGING_LEVEL_SPRINGDOC:debug}"
    springfox: {documentation: "${LOGGING_LEVEL_WEB:debug}"}
    springframework: "${LOGGING_LEVEL_SPRINGFRAMEWORK:debug}"
    web: "${LOGGING_LEVEL_WEB:debug}"
    org.hibernate.orm.deprecation: "${LOGGING_LEVEL_HIBERNATE_ORM:error}"

# api
springdoc:
  default-produces-media-type: "application/hal+json"
  model-and-view-allowed: true
  show-actuator: true
  swagger-ui:
    display-request-duration: true
    path: "/swagger-ui"
    operationsSorter: alpha
